### ISSUE TITLE
AbacusSingleStepSOCParser class from HamiltonIO not found

### ISSUE THREAD

**Issue by jfernandez-cesga** [mailhexu/TB2J#89]
Hi!

I am helping a user with the installation and first steps with TB2J 0.9.17 and right now we are stuck with an error related to a failing import from HamiltonIO:

```
$ wann2J.py --help
Traceback (most recent call last):
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/bin/wann2J.py", line 5, in <module>
    from TB2J.scripts.wann2J import run_wann2J
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/scripts/wann2J.py", line 6, in <module>
    from TB2J.interfaces import gen_exchange
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/interfaces/__init__.py", line 3, in <module>
    from .manager import Manager
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/interfaces/manager.py", line 4, in <module>
    from TB2J.gpu.exchange_ncl_gpu import ExchangeNCLGPU
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/gpu/__init__.py", line 5, in <module>
    from TB2J.gpu.mae_green_gpu import MAEGreenGPU, MAEGreenJAX
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/gpu/mae_green_gpu.py", line 21, in <module>
    from TB2J.MAEGreen import MAEGreen
  File "/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/TB2J/MAEGreen.py", line 6, in <module>
    from HamiltonIO.abacus.abacus_wrapper import (
ImportError: cannot import name 'AbacusSingleStepSOCParser' from 'HamiltonIO.abacus.abacus_wrapper' (/software/2025/easybuild/software/Compiler/gcccore/system/tb2j/0.9.17/lib/python3.11/site-packages/HamiltonIO/abacus/abacus_wrapper.py)
```

As you can see, it tries to import the AbacusSingleStepSOCParser class from HamiltonIO, but our HamiltonIO 0.3.7 installation from PyPI (we tried both source code and wheel file installations) does not include that class in "abacus_wrapper.py". I scanned the HamitonIO repo looking for a specific version or commit including it, but I found nothing.

Is this a kind of a bug or just a matter of incompatible versions of TB2J and HamiltonIO?

Thank you in advance for your help!

**Comment by mailhexu** [comment]
Hello,
Please upgrade HamiltonIO to v0.3.8
pip install -U HamiltonIO

Best regards,
HeXu

**Comment by jfernandez-cesga** [comment]
Hi HeXu,

It works perfectly with 0.3.8, my bad. I use EasyBuild to deploy this, and perhaps at some early stage yesterday when transferring the dependency versions from the log of a manual try using pip to the EasyBuild file, I mistyped 0.3.7 instead of 0.3.8.

Thank you very much for your prompt answer!

**Comment by mailhexu** [comment]
Hi, 
It is actually my fault. I forgot to upload the Hamiltonian v0.3.8 version to pypi. 
Thank you for letting me know the issue. 
Best regards, 
HeXu
